build: false

clone_depth: 1

environment:
  matrix:
  - TARGET: x86_64-pc-windows-msvc
    OTHER_TARGET: i686-pc-windows-msvc
  - TARGET: x86_64-pc-windows-gnu
    OTHER_TARGET: i686-pc-windows-gnu

install:
  - appveyor-retry appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init.exe -y --default-host %TARGET% --default-toolchain stable
  - if "%TARGET%" == "i686-pc-windows-gnu" set PATH=%PATH%;C:\msys64\mingw32\bin
  - if "%TARGET%" == "x86_64-pc-windows-gnu" set PATH=%PATH%;C:\msys64\mingw64\bin
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - rustup target add %OTHER_TARGET%
  - rustc -V
  - cargo -V

test_script:
  - cargo build --verbose --all-features
  - cargo test --verbose --all-features --jobs 4
  - cargo doc --verbose --all-features
